from django.urls import path
from . import views

urlpatterns = [
    path("documentos/<int:pk>.pdf", views.issued_document_pdf, name="issued_document_pdf"),
    path("", views.dashboard, name="dashboard"),
    path("solicitacoes/", views.requests_page, name="requests"),
    path("clientes/rapido/", views.customer_quick_create, name="customer_quick_create"),
    path("solicitacoes/<int:pk>/orcamento/", views.request_quote, name="request_quote"),
    path("solicitacoes/<int:pk>/pedido-direto/", views.request_direct_order, name="request_direct_order"),
    path("orcamentos/", views.quotes_page, name="quotes"),
    path("orcamentos/<int:pk>/salvar/", views.quote_update, name="quote_update"),
    path("orcamentos/<int:pk>.pdf", views.quote_pdf, name="quote_pdf"),
    path("orcamentos/<int:pk>/converter/", views.convert_quote, name="convert_quote"),
    path("pedidos/", views.orders_page, name="orders"),
    path("pedidos/<int:pk>/receber/", views.order_payment, name="order_payment"),
    path("pedidos/<int:pk>/entregar/", views.deliver_order, name="deliver_order"),
    path("producao/", views.production_page, name="production"),
    path("producao/<int:pk>/avancar/", views.production_advance, name="production_advance"),
    path("producao/<int:pk>/falha/", views.production_failure, name="production_failure"),
    path("catalogo/", views.catalog_page, name="catalog"),
    path("estoque/", views.stock_page, name="stock"),
    path("estoque/<int:pk>/reposicao/", views.replenish_product, name="replenish_product"),
    path("materiais/", views.materials_page, name="materials"),
    path("materiais/<int:pk>/abrir-rolo/", views.material_open_roll, name="material_open_roll"),
    path("materiais/<int:pk>/finalizar-rolo/", views.material_close_roll, name="material_close_roll"),
    path("clientes/", views.customers_page, name="customers"),
    path("clientes/<int:pk>/", views.customer_detail, name="customer_detail"),
    path("clientes/<int:pk>/extrato.pdf", views.customer_statement_pdf, name="customer_statement_pdf"),
    path("vendas/nova/", views.pos_page, name="pos"),
    path("consignacao/", views.consignment_page, name="consignment"),
    path("consignacao/remessas/nova/", views.shipment_new, name="shipment_new"),
    path("consignacao/remessas/<int:pk>.pdf", views.shipment_pdf, name="shipment_pdf"),
    path("consignacao/<int:pk>/concluir-remessa/", views.shipment_complete, name="shipment_complete"),
    path("consignacao/<int:pk>/concluir-prestacao/", views.settlement_complete, name="settlement_complete"),
    path("financeiro/", views.finance_page, name="finance"),
    path("financeiro/<int:pk>/liquidar/", views.finance_settle, name="finance_settle"),
    path("relatorios/", views.reports_page, name="reports"),
    path("relatorios/<str:report_type>.pdf", views.report_pdf, name="report_pdf"),
    path("consignacao/prestacao/<int:pk>.pdf", views.consignment_pdf, name="consignment_pdf"),
    path("parametros/", views.settings_page, name="settings"),
    path("composicao/<int:pk>/", views.composition_page, name="composition"),
    path("composicao/<int:pk>/calcular/", views.composition_calculate, name="composition_calculate"),
]
