# Generated by Django 5.2.17 on 2026-08-31 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('slug', models.SlugField(unique=True)),
                ('trading_name', models.CharField(blank=True, max_length=160)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, upload_to='companies/')),
                ('timezone', models.CharField(default='America/Sao_Paulo', max_length=50)),
                ('primary_color', models.CharField(default='#1E40AF', max_length=7)),
                ('secondary_color', models.CharField(default='#F59E0B', max_length=7)),
                ('accent_color', models.CharField(default='#10B981', max_length=7)),
                ('default_filament_minimum', models.PositiveIntegerField(default=2)),
                ('energy_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(max_length=80)),
                ('entity_id', models.CharField(max_length=40)),
                ('action', models.CharField(max_length=50)),
                ('before', models.JSONField(blank=True, default=dict)),
                ('after', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=80)),
                ('result_id', models.CharField(blank=True, max_length=40)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'key', 'operation'), name='unique_operation_key')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('operator', 'Operador'), ('finance', 'Financeiro'), ('viewer', 'Leitura')], default='operator', max_length=16)),
                ('active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'user'), name='unique_company_user')],
            },
        ),
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=4)),
                ('value', models.PositiveBigIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'prefix'), name='unique_company_sequence')],
            },
        ),
    ]
