# Generated by Django 6.0.8 on 2026-09-02 00:27

import django.db.models.deletion
import erp.models
from decimal import Decimal
from django.db import migrations, models


def backfill_correction_data(apps, schema_editor):
    Company = apps.get_model('erp', 'Company')
    Product = apps.get_model('erp', 'Product')
    ProductCategory = apps.get_model('erp', 'ProductCategory')
    ProductType = apps.get_model('erp', 'ProductType')
    Quote = apps.get_model('erp', 'Quote')
    Composition = apps.get_model('erp', 'Composition')
    Order = apps.get_model('erp', 'Order')
    Purchase = apps.get_model('erp', 'Purchase')
    FinancialAccount = apps.get_model('erp', 'FinancialAccount')
    CalculationModel = apps.get_model('erp', 'CalculationModel')

    for company in Company.objects.all():
        default_type, _ = ProductType.objects.get_or_create(company=company, name='Produto próprio')
        for product in Product.objects.filter(company=company):
            category_name = (product.category or 'Sem categoria').strip()
            category, _ = ProductCategory.objects.get_or_create(company=company, name=category_name)
            product.category_ref = category
            product.product_type = default_type
            product.save(update_fields=['category_ref', 'product_type'])
        account = FinancialAccount.objects.filter(company=company, active=True).first()
        if account:
            Purchase.objects.filter(company=company, account__isnull=True).update(account=account)
        CalculationModel.objects.filter(company=company, description='').update(description='Modelo migrado para o motor de bases independentes.')

    for composition in Composition.objects.all():
        composition.base_calculation = composition.total_cost
        composition.direct_cost = composition.total_cost
        composition.margin_base = composition.total_cost
        composition.margin_value = max(Decimal('0'), composition.suggested_price - composition.total_cost)
        composition.save(update_fields=['base_calculation', 'direct_cost', 'margin_base', 'margin_value'])
    for quote in Quote.objects.filter(manual_value__isnull=True).select_related('composition'):
        quote.manual_value = quote.composition.final_price or quote.composition.suggested_price
        quote.save(update_fields=['manual_value'])
    for order in Order.objects.all():
        if not order.actual_cost:
            order.actual_cost = order.predicted_cost
            order.save(update_fields=['actual_cost'])

    praise = Company.objects.filter(slug='praise-3d').first()
    if praise:
        defaults = {
            'document': '59.703.841/0001-08', 'responsible_name': 'Maria Eduarda Bezerra Alves Amaro',
            'phone': '(88) 98121-4692', 'whatsapp': '(88) 98121-4692',
            'email': 'contato@praise3d.com.br', 'instagram': '@praise3doficial',
            'website': 'https://praise3d.com.br', 'city': 'Jaguaribe', 'state': 'CE',
        }
        changed = []
        for field, value in defaults.items():
            if not getattr(praise, field):
                setattr(praise, field, value)
                changed.append(field)
        if changed:
            praise.save(update_fields=changed)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculationmodel',
            name='component_rules',
            field=models.JSONField(blank=True, default=erp.models.default_component_rules),
        ),
        migrations.AddField(
            model_name='calculationmodel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='phone',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='company',
            name='responsible_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='company',
            name='state_registration',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company',
            name='warning_color',
            field=models.CharField(default='#ef4444', max_length=7),
        ),
        migrations.AddField(
            model_name='company',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='composition',
            name='base_calculation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='composition',
            name='direct_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='composition',
            name='maintenance_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='composition',
            name='margin_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='composition',
            name='margin_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='consignmentsettlementitem',
            name='disposition',
            field=models.CharField(choices=[('remain', 'Permanecer consignado'), ('return', 'Retornar ao estoque central')], default='remain', max_length=12),
        ),
        migrations.AddField(
            model_name='materialmovement',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='printer',
            name='maintenance_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Manutenção por hora'),
        ),
        migrations.AddField(
            model_name='productiondemand',
            name='reserved_supplies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='productionfailure',
            name='failure_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='productionfailure',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='failures', to='erp.manufacturingpart'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='erp.financialaccount'),
        ),
        migrations.AddField(
            model_name='quote',
            name='freight_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='quote',
            name='manual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddField(
            model_name='supply',
            name='reserved_stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='productiondemand',
            name='stage',
            field=models.CharField(choices=[('art', 'Fazer arte'), ('material', 'Aguardando material'), ('queue', 'Aguardando impressão'), ('printing', 'Imprimindo'), ('ready', 'Pronto')], max_length=12),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='erp.productcategory'),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='erp.producttype'),
        ),
        migrations.CreateModel(
            name='IssuedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=40)),
                ('reference_id', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=180)),
                ('content', models.BinaryField()),
                ('content_hash', models.CharField(max_length=64)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_documents', to='erp.company')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'document_type', 'reference_id'), name='uniq_issued_document')],
            },
        ),
        migrations.RunPython(backfill_correction_data, noop_reverse),
        migrations.AddConstraint(
            model_name='productcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_product_category'),
        ),
        migrations.AddConstraint(
            model_name='producttype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_product_type'),
        ),
    ]
