# Generated by Django 6.0.8 on 2026-09-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_calculationmodel_component_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productiondemand',
            name='item_name',
            field=models.TextField(),
        ),
    ]
