# Generated by Django 6.0.8 on 2026-09-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_order_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composition',
            name='margin_override',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='waste_override',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True),
        ),
    ]
