# Generated by Django 6.0.8 on 2026-09-03 00:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_composition_margin_override_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentshipment',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='priority_level',
            field=models.CharField(choices=[('normal', 'Normal'), ('priority', 'Prioritário'), ('urgent', 'Urgente')], default='normal', max_length=12),
        ),
        migrations.AddField(
            model_name='productiondemand',
            name='composition_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='erp.compositionitem'),
        ),
        migrations.AddField(
            model_name='productiondemand',
            name='consumed_supplies',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchase',
            name='source_demand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='erp.productiondemand'),
        ),
        migrations.CreateModel(
            name='RequestReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_at', models.DateTimeField()),
                ('scheduled_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('due', 'Vencido'), ('snoozed', 'Adiado'), ('completed', 'Concluído'), ('cancelled', 'Cancelado')], default='scheduled', max_length=12)),
                ('purpose', models.CharField(choices=[('manual', 'Retornar contato / tarefa manual'), ('quote', 'Criar orçamento'), ('order', 'Gerar pedido')], default='manual', max_length=12)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_mode', models.CharField(blank=True, max_length=24)),
                ('version', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assigned_reminders', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_reminders', to=settings.AUTH_USER_MODEL)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reminder', to='erp.quoterequest')),
            ],
            options={
                'ordering': ['scheduled_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('kind', models.CharField(max_length=48)),
                ('description', models.TextField()),
                ('source_model', models.CharField(max_length=64)),
                ('source_id', models.PositiveBigIntegerField()),
                ('event_key', models.CharField(max_length=180)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='erp.customer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='erp.order')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activity_events', to='erp.quoterequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-happened_at', '-pk'],
                'constraints': [models.UniqueConstraint(fields=('company', 'event_key'), name='uniq_activity_event')],
            },
        ),
        migrations.CreateModel(
            name='ArchivedRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_model', models.CharField(max_length=64)),
                ('source_id', models.PositiveBigIntegerField()),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archived', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company', 'source_model', 'source_id'), name='uniq_archived_record')],
            },
        ),
    ]
