# Generated by Django 6.0.8 on 2026-09-04 20:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_correction4(apps, schema_editor):
    FinancialAccount = apps.get_model('erp', 'FinancialAccount')
    Purchase = apps.get_model('erp', 'Purchase')
    Company = apps.get_model('erp', 'Company')
    FinancialAccount.objects.filter(kind='bank').update(kind='checking')
    for company in Company.objects.all():
        account = FinancialAccount.objects.filter(company=company, active=True).order_by('pk').first()
        if account:
            FinancialAccount.objects.filter(pk=account.pk).update(is_default=True)
    for purchase in Purchase.objects.prefetch_related('items').all():
        if purchase.cancelled_at:
            status = 'cancelled'
        elif purchase.completed_at:
            status = 'effected'
        else:
            status = 'pending' if purchase.items.exists() else 'draft'
        purchase_type = 'filament' if purchase.items.filter(filament__isnull=False).exists() else 'supply'
        Purchase.objects.filter(pk=purchase.pk).update(status=status, purchase_type=purchase_type)


def reverse_backfill(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0006_backfill_operational_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialaccount',
            options={'ordering': ['-is_default', 'name']},
        ),
        migrations.AddField(
            model_name='company',
            name='order_advance_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=7),
        ),
        migrations.AddField(
            model_name='company',
            name='receivable_days_after_completion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='require_order_advance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='consignedstore',
            name='city',
            field=models.CharField(blank=True, max_length=90),
        ),
        migrations.AddField(
            model_name='consignedstore',
            name='complement',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='consignedstore',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='consignedstore',
            name='postal_code',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='consignedstore',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='consignedstore',
            name='street_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='institution',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='financialaccount',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manufacturingpart',
            name='plate_quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Qnt. na mesa'),
        ),
        migrations.AddField(
            model_name='product',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deactivated_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='operational_activity',
            field=models.BooleanField(default=True, verbose_name='Em atividade'),
        ),
        migrations.AddField(
            model_name='productiondemand',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productiondemand',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_production_demands', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_type',
            field=models.CharField(choices=[('filament', 'Filamento'), ('supply', 'Insumo')], default='supply', max_length=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Pendente de efetivação'), ('effected', 'Efetivada'), ('cancelled', 'Cancelada')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.CharField(blank=True, default='Estoque central', max_length=180),
        ),
        migrations.AlterField(
            model_name='financialaccount',
            name='kind',
            field=models.CharField(choices=[('cash', 'Caixa'), ('checking', 'Conta corrente'), ('digital', 'Conta digital'), ('wallet', 'Carteira'), ('other', 'Outro')], default='checking', max_length=16),
        ),
        migrations.AlterField(
            model_name='financialentry',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='erp.financialaccount'),
        ),
        migrations.RunPython(backfill_correction4, reverse_backfill),
        migrations.AddConstraint(
            model_name='financialaccount',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='uniq_default_financial_account'),
        ),
    ]
