# Generated by Django 5.2.17 on 2026-08-31 02:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('version', models.PositiveIntegerField(default=1)),
                ('mode', models.CharField(choices=[('margin', 'Margem'), ('markup', 'Markup')], default='markup', max_length=10)),
                ('rate', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('components', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('filament', 'Filamento'), ('supply', 'Insumo')], max_length=12)),
                ('name', models.CharField(max_length=140)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('brand', models.CharField(blank=True, max_length=80)),
                ('diameter', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('nominal_weight', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('unit', models.CharField(default='un', max_length=20)),
                ('supplier', models.CharField(blank=True, max_length=140)),
                ('roll_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('minimum', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('physical_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reserved_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('closed_rolls', models.PositiveIntegerField(default=0)),
                ('open_rolls', models.PositiveIntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('purchase', 'Compra'), ('open', 'Abertura'), ('finish', 'Finalização'), ('reserve', 'Reserva'), ('consume', 'Consumo'), ('release', 'Liberação'), ('adjust', 'Ajuste'), ('reverse', 'Estorno')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('source_type', models.CharField(blank=True, max_length=40)),
                ('source_id', models.CharField(blank=True, max_length=40)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('useful_life_hours', models.PositiveIntegerField(default=10000)),
                ('residual_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('power_watts', models.PositiveIntegerField(default=350)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=180)),
                ('sku', models.CharField(max_length=40)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='products/')),
                ('technical_sheet', models.JSONField(default=dict)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('minimum_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('target_stock', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('calculation_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.calculationmodel')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('type', models.CharField(choices=[('production', 'Produção'), ('sale', 'Venda'), ('consignment', 'Consignação'), ('return', 'Retorno'), ('loss', 'Perda'), ('adjust', 'Ajuste'), ('transfer', 'Transferência'), ('reverse', 'Estorno')], max_length=16)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('source_type', models.CharField(max_length=40)),
                ('source_id', models.CharField(max_length=40)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('balance_after', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('company', 'sku'), name='unique_company_sku'),
        ),
    ]
