# Generated by Django 5.2.17 on 2026-08-31 02:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=12)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('priority', models.BooleanField(default=False)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('predicted_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commercial_status', models.CharField(default='confirmed', max_length=16)),
                ('financial_status', models.CharField(default='pending', max_length=16)),
                ('calculation_status', models.CharField(default='pending', max_length=16)),
                ('snapshot', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionDemand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('stage', models.CharField(choices=[('art', 'Fazer arte'), ('material', 'Aguardando material'), ('queue', 'Aguardando impressão'), ('printing', 'Imprimindo'), ('ready', 'Pronto')], default='art', max_length=12)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demands', to='operations.order')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.printer')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductionFailure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('reason', models.CharField(max_length=180)),
                ('additional_grams', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('additional_minutes', models.PositiveIntegerField(default=0)),
                ('additional_supplies', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failures', to='operations.productiondemand')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=12)),
                ('status', models.CharField(default='draft', max_length=20)),
                ('valid_until', models.DateField(null=True)),
                ('discount_percent', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('predicted_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('suggested_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('predicted_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('cost_snapshot', models.JSONField(default=dict)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='operations.quote'),
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('description', models.CharField(max_length=220)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('color', models.CharField(blank=True, max_length=60)),
                ('grams', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('print_minutes', models.PositiveIntegerField(default=0)),
                ('supplies', models.JSONField(default=list)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('snapshot', models.JSONField(default=dict)),
                ('calculation_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.calculationmodel')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.material')),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.printer')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.quote')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=220)),
                ('notes', models.TextField(blank=True)),
                ('origin', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('in_person', 'Presencial'), ('phone', 'Telefone'), ('referral', 'Indicação'), ('other', 'Outro')], max_length=12)),
                ('reminder_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='new', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.company')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.customer')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='operations.quoterequest'),
        ),
        migrations.AddField(
            model_name='order',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.quoterequest'),
        ),
        migrations.AddConstraint(
            model_name='quoterequest',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_request_code'),
        ),
        migrations.AddConstraint(
            model_name='quote',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_quote_code'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_order_code'),
        ),
    ]
